import React from 'react';
import { 
  Globe, 
  StickyNote, 
  Settings, 
  Camera, 
  Image as ImageIcon, 
  Mail,
  Wifi,
  Battery,
  Search,
  ArrowLeft,
  ArrowRight,
  RefreshCw,
  X,
  Maximize2,
  Minus,
  ShoppingBag,
  ChevronRight,
  User,
  Bell,
  Moon,
  Sun,
  Bluetooth,
  Shield,
  Smartphone,
  Gamepad2,
  Trophy,
  Play,
  Table,
  Grid,
  List,
  Trash2,
  Download,
  Star,
  Save,
  Plus,
  LayoutGrid,
  Power,
  Sparkles,
  Command,
  Cat
} from 'lucide-react';

export const Icons = {
  Browser: Globe,
  Cat: Cat,
  Notes: StickyNote,
  Settings: Settings,
  Camera: Camera,
  Photos: ImageIcon,
  Mail: Mail,
  Wifi: Wifi,
  Battery: Battery,
  Search: Search,
  Back: ArrowLeft,
  Forward: ArrowRight,
  Refresh: RefreshCw,
  Close: X,
  Maximize: Maximize2,
  Minimize: Minus,
  AppStore: ShoppingBag,
  ChevronRight: ChevronRight,
  User: User,
  Bell: Bell,
  Moon: Moon,
  Sun: Sun,
  Bluetooth: Bluetooth,
  Privacy: Shield,
  Device: Smartphone,
  Game: Gamepad2,
  Trophy: Trophy,
  Play: Play,
  Excel: Table,
  Grid: Grid,
  List: List,
  Trash: Trash2,
  Download: Download,
  Star: Star,
  Save: Save,
  Plus: Plus,
  Start: LayoutGrid,
  Power: Power,
  AI: Sparkles,
  Command: Command
};